// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyegoK0mB7mbZeu_fj4VpEFge-zFKhit4',
    appId: '1:527210304558:web:cbddff8bf9fd16f985bbbf',
    messagingSenderId: '527210304558',
    projectId: 'runtod-app',
    authDomain: 'runtod-app.firebaseapp.com',
    storageBucket: 'runtod-app.appspot.com',
    measurementId: 'G-6PJVJ39F11',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNwXpa2C6Xy4EI4BMyVXWfUUvnShZb_qs',
    appId: '1:527210304558:android:b1c52db65cedcfd985bbbf',
    messagingSenderId: '527210304558',
    projectId: 'runtod-app',
    storageBucket: 'runtod-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxgFr4edvLmUwothS8kp3OWQmFSzVS5LY',
    appId: '1:527210304558:ios:fe662cb62578764985bbbf',
    messagingSenderId: '527210304558',
    projectId: 'runtod-app',
    storageBucket: 'runtod-app.appspot.com',
    iosBundleId: 'com.example.runtodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxgFr4edvLmUwothS8kp3OWQmFSzVS5LY',
    appId: '1:527210304558:ios:fe662cb62578764985bbbf',
    messagingSenderId: '527210304558',
    projectId: 'runtod-app',
    storageBucket: 'runtod-app.appspot.com',
    iosBundleId: 'com.example.runtodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyegoK0mB7mbZeu_fj4VpEFge-zFKhit4',
    appId: '1:527210304558:web:b614b18eb7ae616d85bbbf',
    messagingSenderId: '527210304558',
    projectId: 'runtod-app',
    authDomain: 'runtod-app.firebaseapp.com',
    storageBucket: 'runtod-app.appspot.com',
    measurementId: 'G-YH1HZ3WMY3',
  );
}
